name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android:
   name: Android
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v2
     with:
          fetch-depth: 0
          submodules: recursive
   - uses: actions/checkout@v3
   - uses: actions/setup-java@v3
     with:
      distribution: 'zulu' # See 'Supported distributions' for available options
      java-version: '8'
   - uses: nttld/setup-ndk@v1
     id: setup-ndk
     with:
      ndk-version: r10e
      add-to-path: false
   - run: |
           sudo dpkg --add-architecture i386
           sudo apt update
           sudo apt install gcc-multilib g++-multilib gcc:i386 -y
           ./build
     env:
      ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
   - name: Upload artifacts
     uses: actions/upload-artifact@v2
     with:
          name: Android
          path: libs/armeabi-v7a/libclient_hardfp.so
   - name: Upload artifacts
     uses: actions/upload-artifact@v2
     with:
          name: Android
          path: libs/armeabi-v7a/libyapb_hardfp.so
